apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes-demo
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:latest
---
apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-public
  namespace: default
spec:
  type: NodePort
  selector:
    app: hello-kubernetes
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001